name: DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t flask-api:latest .

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint k8s/

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy - Scan des dependances (filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'LOW,MEDIUM,HIGH,CRITICAL'

      - name: Build Docker image
        run: docker build -t flask-api:latest .

      - name: Trivy - Scan de l image Docker
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'flask-api:latest'
          format: 'table'
          severity: 'LOW,MEDIUM,HIGH,CRITICAL'

  policy-check:
      runs-on: ubuntu-latest
      needs: build-and-lint

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install Conftest
          run: |
            wget -q https://github.com/open-policy-agent/conftest/releases/download/v0.46.0/conftest_0.46.0_Linux_x86_64.tar.gz
            tar xzf conftest_0.46.0_Linux_x86_64.tar.gz
            sudo mv conftest /usr/local/bin/

        - name: Run Conftest on Kubernetes manifests
          run: conftest test k8s/deployment.yaml --policy policy/